Repository mash-up-kr/chinchin-android, pull requests merged in 2022-08, with the labels that each got.

#53 #47 bottom sheet 구현
  presenter/src/main/java/com/mashup/chinchin/presenter/main/MainActivity.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/reply_preference/ReplyPreferenceActivity.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/send_preference/SendPreferenceActivity.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/main/MainNavGraph.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/main/recommend_friends/RecommendFriendsComponent.kt
  presenter/src/main/java/com/mashup/presenter/ui/common/bottom_sheet/BottomSheetComponent.kt
  presenter/src/main/java/com/mashup/presenter/ui/common/bottom_sheet/model/BottomSheetItemUiModel.kt
  presenter/src/main/res/drawable/ic_save.xml
  presenter/src/main/res/drawable/ic_send.xml
  presenter/src/main/res/drawable/icon_connect.xml
Labels: feat

#50 취향질문지 보내기 다이얼로그와 연결
  presenter/src/main/java/com/mashup/chinchin/presenter/common/ChinChinQuestionCardState.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/common/model/CategoryUiModel.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/common/model/KeywordQuestionUiModel.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/send_preference/SendPreferenceActivity.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/ChinChinComponent.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/send_questions/SendPreferenceComponent.kt
Labels: feat

#76 그룹 추가하기 다이얼로그 수정
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/add_friend/AddFriendComponent.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/ChinChinComponent.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/set_group/SetGroupComponent.kt
Labels: enhancement

#77 질문지 보내기 페이지 문구수정
  presenter/src/main/java/com/mashup/chinchin/presenter/send_preference/SendPreferenceCompleteActivity.kt
  presenter/src/main/res/drawable/illust_6_1.png
  presenter/src/main/res/drawable/send_complete.png
Labels: enhancement

#73 #58 메인화면에 존재하는 탭들 네비게이션 높이만큼 위로 올리기
  presenter/src/main/java/com/mashup/chinchin/presenter/main/MainActivity.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/main/MainNavGraph.kt
Labels: bug

#80 feat: #79 친구 디테일 collapsing-toolbar, ui 일부 수정
  presenter/src/main/java/com/mashup/chinchin/presenter/friend_detail/FriendDetailActivity.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/common/ChinChinComponent.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/friend_detail/FriendDetailContentComponent.kt
  presenter/src/main/java/com/mashup/chinchin/presenter/ui/friend_detail/FriendDetailTopBarComponent.kt
Labels: enhancement

#85 #68 more page 구현
  presenter/src/main/java/com/mashup/chinchin/presenter/main/MainActivity.kt
Labels: enhancement
